MAX_N_FRAGMENTS: 200
TOLERANCE_DALTON: 0.01
MIN_MATCHING_PEAKS : 4
MAX_N_PEAKS: 100
BATCH_SIZE: 64
NUMBER_OF_THREADS: 64
K: 50
FDR: 0.01
MIN_DELTA_MASS: -150.
MAX_DELTA_MASS: 500.

MIN_PEPTIDE_MASS: 500.
MAX_PEPTIDE_MASS: 5000.
N_BUCKETS: 2250